<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MatchesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. karta
        \App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '2',
        'referee_id' => '1',
        'date' => '2025-03-05 18:00:00',
        'matchweek' => '1',
        'homegoals' => '1',
        'awaygoals' => '2',
        'stadium' => 'Mežaparks SV',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '9',
        'referee_id' => '2',
        'date' => '2025-03-06 18:00:00',
        'matchweek' => '1',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Mežaparks SV',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '6',
        'referee_id' => '3',
        'date' => '2025-03-06 18:00:00',
        'matchweek' => '1',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '10',
        'referee_id' => '4',
        'date' => '2025-03-07 17:30:00',
        'matchweek' => '1',
        'homegoals' => '3',
        'awaygoals' => '0',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '8',
        'referee_id' => '5',
        'date' => '2025-03-07 18:30:00',
        'matchweek' => '1',
        'homegoals' => '4',
        'awaygoals' => '0',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
        'info' => '1',
    ]);
    //2. karta
        \App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '3',
        'referee_id' => '6',
        'date' => '2025-03-10 19:00:00',
        'matchweek' => '2',
        'homegoals' => '2',
        'awaygoals' => '2',
        'stadium' => 'Mežaparks SV',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '4',
        'referee_id' => '5',
        'date' => '2025-03-11 18:00:00',
        'matchweek' => '2',
        'homegoals' => '3',
        'awaygoals' => '2',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '6',
        'referee_id' => '7',
        'date' => '2025-03-11 19:00:00',
        'matchweek' => '2',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'LNK Sporta Parks (mākslīgais)',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '10',
        'referee_id' => '8',
        'date' => '2025-03-12 18:00:00',
        'matchweek' => '2',
        'homegoals' => '0',
        'awaygoals' => '0',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
        'info' => '1',
    ]);
        \App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '8',
        'referee_id' => '4',
        'date' => '2025-03-12 19:00:00',
        'matchweek' => '2',
        'homegoals' => '4',
        'awaygoals' => '0',
        'stadium' => 'LNK Sporta Parks (mākslīgais)',
        'info' => '1',
    ]);
    //3. karta
        \App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '1',
        'referee_id' => '4',
        'date' => '2025-03-15 14:00:00',
        'matchweek' => '3',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'FK Jelgava Sporta bāzes mākslīgais laukums',
        'info' => '1',
    ]);\App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '2',
        'referee_id' => '8',
        'date' => '2025-03-15 16:00:00',
        'matchweek' => '3',
        'homegoals' => '1',
        'awaygoals' => '2',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
        'info' => '1',
    ]);\App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '10',
        'referee_id' => '7',
        'date' => '2025-03-16 13:00:00',
        'matchweek' => '3',
        'homegoals' => '3',
        'awaygoals' => '2',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
        'info' => '1',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '9',
        'referee_id' => '3',
        'date' => '2025-03-16 17:00:00',
        'matchweek' => '3',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'Mežaparks SV',
        'info' => '1',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '5',
        'referee_id' => '5',
        'date' => '2025-03-16 19:00:00',
        'matchweek' => '3',
        'homegoals' => '4',
        'awaygoals' => '1',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
        'info' => '1',
    ]);
    //4.karta
        \App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '4',
        'referee_id' => '9',
        'date' => '2025-03-29 15:00:00',
        'matchweek' => '4',
        'homegoals' => '1',
        'awaygoals' => '2',
        'stadium' => 'Mežaparks SV',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '7',
        'referee_id' => '6',
        'date' => '2025-03-29 17:00:00',
        'matchweek' => '4',
        'homegoals' => '4',
        'awaygoals' => '1',
        'stadium' => 'LNK Sporta Parks (mākslīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '8',
        'referee_id' => '10',
        'date' => '2025-03-30 15:00:00',
        'matchweek' => '4',
        'homegoals' => '2',
        'awaygoals' => '4',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '6',
        'referee_id' => '11',
        'date' => '2025-03-30 17:00:00',
        'matchweek' => '4',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Mežaparks SV',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '9',
        'referee_id' => '12',
        'date' => '2025-03-31 17:00:00',
        'matchweek' => '4',
        'homegoals' => '2',
        'awaygoals' => '2',
        'stadium' => 'Tukuma pils. stad. māksl. lauk.',
    ]);           
    //5. karta
        \App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '1',
        'referee_id' => '1',
        'date' => '2025-04-03 18:00:00',
        'matchweek' => '5',
        'homegoals' => '2',
        'awaygoals' => '5',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '2',
        'referee_id' => '2',
        'date' => '2025-04-04 17:00:00',
        'matchweek' => '5',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '3',
        'referee_id' => '12',
        'date' => '2025-04-04 18:00:00',
        'matchweek' => '5',
        'homegoals' => '2',
        'awaygoals' => '1',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '5',
        'referee_id' => '9',
        'date' => '2025-04-05 14:00:00',
        'matchweek' => '5',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Tukuma pils. stad. māksl. lauk.',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '9',
        'referee_id' => '3',
        'date' => '2025-04-05 16:00:00',
        'matchweek' => '5',
        'homegoals' => '2',
        'awaygoals' => '1',
        'stadium' => 'FK Jelgava Sporta bāzes mākslīgais laukums',
    ]);
    //6.karta
    \App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '8',
        'referee_id' => '4',
        'date' => '2025-04-08 19:00:00',
        'matchweek' => '6',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Mežaparks SV',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '7',
        'referee_id' => '7',
        'date' => '2025-04-09 18:00:00',
        'matchweek' => '6',
        'homegoals' => '3',
        'awaygoals' => '0',
        'stadium' => 'Mežaparks SV',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '10',
        'referee_id' => '11',
        'date' => '2025-04-09 19:00:00',
        'matchweek' => '6',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'LNK Sporta Parks (mākslīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '4',
        'referee_id' => '5',
        'date' => '2025-04-10 17:30:00',
        'matchweek' => '6',
        'homegoals' => '4',
        'awaygoals' => '1',
        'stadium' => 'FK Jelgava Sporta bāzes mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '5',
        'referee_id' => '6',
        'date' => '2025-04-10 19:00:00',
        'matchweek' => '6',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'LNK Sporta Parks (mākslīgais)',
    ]);
    //7.karta
    \App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '3',
        'referee_id' => '2',
        'date' => '2025-04-13 14:00:00',
        'matchweek' => '7',
        'homegoals' => '0',
        'awaygoals' => '1',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '1',
        'referee_id' => '10',
        'date' => '2025-04-13 16:00:00',
        'matchweek' => '7',
        'homegoals' => '0',
        'awaygoals' => '3',
        'stadium' => 'Tukuma pils. stad. māksl. lauk.',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '6',
        'referee_id' => '11',
        'date' => '2025-04-14 18:00:00',
        'matchweek' => '7',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '2',
        'referee_id' => '3',
        'date' => '2025-04-15 18:00:00',
        'matchweek' => '7',
        'homegoals' => '1',
        'awaygoals' => '4',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '9',
        'referee_id' => '7',
        'date' => '2025-04-15 19:00:00',
        'matchweek' => '7',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);
    //8.karta
    \App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '6',
        'referee_id' => '5',
        'date' => '2025-04-18 15:00:00',
        'matchweek' => '8',
        'homegoals' => '0',
        'awaygoals' => '0',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '10',
        'referee_id' => '3',
        'date' => '2025-04-18 17:00:00',
        'matchweek' => '8',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Mežaparks SV',
    ]);\App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '7',
        'referee_id' => '6',
        'date' => '2025-04-19 14:00:00',
        'matchweek' => '8',
        'homegoals' => '4',
        'awaygoals' => '2',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '5',
        'referee_id' => '2',
        'date' => '2025-04-19 16:00:00',
        'matchweek' => '8',
        'homegoals' => '3',
        'awaygoals' => '0',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '2',
        'referee_id' => '10',
        'date' => '2025-04-20 17:00:00',
        'matchweek' => '8',
        'homegoals' => '1',
        'awaygoals' => '2',
        'stadium' => 'LNK Sporta Parks (mākslīgais)',
    ]);
    //9.karta
    \App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '10',
        'referee_id' => '4',
        'date' => '2025-04-23 18:00:00',
        'matchweek' => '9',
        'homegoals' => '2',
        'awaygoals' => '1',
        'stadium' => 'FK Jelgava Sporta bāzes mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '5',
        'referee_id' => '11',
        'date' => '2025-04-24 18:00:00',
        'matchweek' => '9',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Mežaparks SV',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '9',
        'referee_id' => '2',
        'date' => '2025-04-25 18:00:00',
        'matchweek' => '9',
        'homegoals' => '2',
        'awaygoals' => '2',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '8',
        'referee_id' => '6',
        'date' => '2025-04-25 19:00:00',
        'matchweek' => '9',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '1',
        'referee_id' => '3',
        'date' => '2025-04-26 18:00:00',
        'matchweek' => '9',
        'homegoals' => '0',
        'awaygoals' => '1',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);
    //10.karta
    \App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '5',
        'referee_id' => '7',
        'date' => '2025-04-29 18:00:00',
        'matchweek' => '10',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'FK Jelgava Sporta bāzes mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '4',
        'referee_id' => '5',
        'date' => '2025-04-30 18:00:00',
        'matchweek' => '10',
        'homegoals' => '0',
        'awaygoals' => '0',
        'stadium' => 'Tukuma pils. stad. māksl. lauk.',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '1',
        'referee_id' => '12',
        'date' => '2025-05-01 13:00:00',
        'matchweek' => '10',
        'homegoals' => '1',
        'awaygoals' => '5',
        'stadium' => 'LNK Sporta Parks (mākslīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '3',
        'referee_id' => '9',
        'date' => '2025-05-01 19:00:00',
        'matchweek' => '10',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '7',
        'referee_id' => '1',
        'date' => '2025-05-02 15:00:00',
        'matchweek' => '10',
        'homegoals' => '2',
        'awaygoals' => '4',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
    ]);
    //11.karta
        \App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '4',
        'referee_id' => '12',
        'date' => '2025-05-04 16:00:00',
        'matchweek' => '11',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'Stadions "Daugava", rezerves laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '2',
        'referee_id' => '1',
        'date' => '2025-05-05 14:00:00',
        'matchweek' => '11',
        'homegoals' => '2',
        'awaygoals' => '2',
        'stadium' => 'FK Jelgava Sporta bāzes mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '1',
        'referee_id' => '3',
        'date' => '2025-05-05 16:00:00',
        'matchweek' => '11',
        'homegoals' => '1',
        'awaygoals' => '3',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '9',
        'referee_id' => '7',
        'date' => '2025-05-06 18:00:00',
        'matchweek' => '11',
        'homegoals' => '0',
        'awaygoals' => '2',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '7',
        'referee_id' => '10',
        'date' => '2025-05-06 18:00:00',
        'matchweek' => '11',
        'homegoals' => '2',
        'awaygoals' => '2',
        'stadium' => 'Tukuma pils. stad. māksl. lauk.',
    ]);
    //12.karta
        \App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '4',
        'referee_id' => '2',
        'date' => '2025-05-09 19:00:00',
        'matchweek' => '12',
        'homegoals' => '5',
        'awaygoals' => '1',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '7',
        'referee_id' => '1',
        'date' => '2025-05-10 16:00:00',
        'matchweek' => '12',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '6',
        'referee_id' => '9',
        'date' => '2025-05-10 18:00:00',
        'matchweek' => '12',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '8',
        'referee_id' => '11',
        'date' => '2025-05-11 14:00:00',
        'matchweek' => '12',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Tukuma pils. stad. māksl. lauk.',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '3',
        'referee_id' => '12',
        'date' => '2025-05-11 19:00:00',
        'matchweek' => '12',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Jāņa Skredeļa stadions',
    ]);
    //11.karta 
        \App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '1',
        'referee_id' => '1',
        'date' => '2025-05-14 17:30:00',
        'matchweek' => '13',
        'homegoals' => '0',
        'awaygoals' => '1',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '2',
        'referee_id' => '6',
        'date' => '2025-05-14 18:00:00',
        'matchweek' => '13',
        'homegoals' => '2',
        'awaygoals' => '1',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '3',
        'referee_id' => '4',
        'date' => '2025-05-15 18:00:00',
        'matchweek' => '13',
        'homegoals' => '3',
        'awaygoals' => '1',
        'stadium' => 'Zemgales OC',
    ]);\App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '5',
        'referee_id' => '10',
        'date' => '2025-05-15 18:30:00',
        'matchweek' => '13',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '10',
        'referee_id' => '3',
        'date' => '2025-05-16 19:00:00',
        'matchweek' => '13',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Jāņa Skredeļa stadions',
    ]);
    //14.karta
        \App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '7',
        'referee_id' => '12',
        'date' => '2025-05-19 19:00:00',
        'matchweek' => '14',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '4',
        'referee_id' => '3',
        'date' => '2025-05-20 18:00:00',
        'matchweek' => '14',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '8',
        'referee_id' => '7',
        'date' => '2025-05-20 20:00:00',
        'matchweek' => '14',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '10',
        'referee_id' => '2',
        'date' => '2025-05-21 18:00:00',
        'matchweek' => '14',
        'homegoals' => '2',
        'awaygoals' => '0',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '6',
        'referee_id' => '6',
        'date' => '2025-05-21 20:00:00',
        'matchweek' => '14',
        'homegoals' => '0',
        'awaygoals' => '0',
        'stadium' => 'Jāņa Skredeļa stadions',
    ]);
    //15.karta
        \App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '1',
        'referee_id' => '3',
        'date' => '2025-05-24 16:00:00',
        'matchweek' => '15',
        'homegoals' => '0',
        'awaygoals' => '3',
        'stadium' => 'Rīgas Hanzas vidusskolas futbola laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '3',
        'referee_id' => '12',
        'date' => '2025-05-24 18:00:00',
        'matchweek' => '15',
        'homegoals' => '0',
        'awaygoals' => '0',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '6',
        'referee_id' => '2',
        'date' => '2025-05-25 16:00:00',
        'matchweek' => '15',
        'homegoals' => '1',
        'awaygoals' => '0',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '2',
        'referee_id' => '4',
        'date' => '2025-05-25 18:00:00',
        'matchweek' => '15',
        'homegoals' => '2',
        'awaygoals' => '5',
        'stadium' => 'Tukuma pilsētas stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '9',
        'referee_id' => '5',
        'date' => '2025-05-26 18:00:00',
        'matchweek' => '15',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);
    //16.karta
        \App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '8',
        'referee_id' => '6',
        'date' => '2025-05-29 18:00:00',
        'matchweek' => '16',
        'homegoals' => '4',
        'awaygoals' => '1',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '7',
        'referee_id' => '5',
        'date' => '2025-05-30 18:00:00',
        'matchweek' => '16',
        'homegoals' => '0',
        'awaygoals' => '1',
        'stadium' => 'Zemgales OC',
    ]);\App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '10',
        'referee_id' => '10',
        'date' => '2025-05-31 17:00:00',
        'matchweek' => '16',
        'homegoals' => '3',
        'awaygoals' => '0',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '5',
        'referee_id' => '1',
        'date' => '2025-05-31 19:00:00',
        'matchweek' => '16',
        'homegoals' => '6',
        'awaygoals' => '0',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '4',
        'referee_id' => '7',
        'date' => '2025-06-01 15:00:00',
        'matchweek' => '16',
        'homegoals' => '4',
        'awaygoals' => '1',
        'stadium' => 'Jāņa Skredeļa stadions',
    ]);
    //17.karta
        \App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '3',
        'referee_id' => '6',
        'date' => '2025-06-13 18:00:00',
        'matchweek' => '17',
        'homegoals' => '2',
        'awaygoals' => '4',
        'stadium' => 'Tukuma pilsētas stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '4',
        'referee_id' => '1',
        'date' => '2025-06-13 18:00:00',
        'matchweek' => '17',
        'homegoals' => '1',
        'awaygoals' => '1',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '8',
        'referee_id' => '4',
        'date' => '2025-06-13 19:00:00',
        'matchweek' => '17',
        'homegoals' => '2',
        'awaygoals' => '1',
        'stadium' => 'Zemgales OC',
    ]);\App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '1',
        'referee_id' => '7',
        'date' => '2025-06-14 14:00:00',
        'matchweek' => '17',
        'homegoals' => '0',
        'awaygoals' => '2',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '9',
        'referee_id' => '3',
        'date' => '2025-06-14 20:00:00',
        'matchweek' => '17',
        'homegoals' => '2',
        'awaygoals' => '1',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);
    //18.karta - notiek tagad




    //Upcoming. - 19.karta
        \App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '10',
        'date' => '2025-06-21 16:00:00',
        'matchweek' => '19',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '8',
        'date' => '2025-06-21 18:00:00',
        'matchweek' => '19',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '5',
        'date' => '2025-06-22 16:00:00',
        'matchweek' => '19',
        'stadium' => 'Zemgales OC',
    ]);\App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '9',
        'date' => '2025-06-22 18:00:00',
        'matchweek' => '19',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '3',
        'date' => '2025-06-22 20:00:00',
        'matchweek' => '19',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);
    //Upcoming. - 20.karta
        \App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '7',
        'date' => '2025-06-25 19:00:00',
        'matchweek' => '20',
        'stadium' => 'Tukuma pilsētas stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '5',
        'date' => '2025-06-26 18:00:00',
        'matchweek' => '20',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '2',
        'date' => '2025-06-26 19:00:00',
        'matchweek' => '20',
        'stadium' => 'Zemgales OC',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '1',
        'date' => '2025-06-27 18:00:00',
        'matchweek' => '20',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '8',
        'date' => '2025-06-27 20:00:00',
        'matchweek' => '20',
        'stadium' => 'Jāņa Skredeļa stadions',
    ]);
    //Upcoming. - 21.karta
        \App\Models\matches::create([
        'home_team_id' => '4',
        'away_team_id' => '2',
        'date' => '2025-06-30 18:00:00',
        'matchweek' => '21',
        'stadium' => 'Stadions "Esplanāde", mākslīgais laukums',
    ]);\App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '5',
        'date' => '2025-06-30 20:00:00',
        'matchweek' => '21',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '3',
        'date' => '2025-07-01 18:00:00',
        'matchweek' => '21',
        'stadium' => 'Jāņa Skredeļa stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '6',
        'date' => '2025-07-01 20:00:00',
        'matchweek' => '21',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '10',
        'date' => '2025-07-02 19:00:00',
        'matchweek' => '21',
        'stadium' => 'Jūrmalas pilsētas stadions "Sloka"',
    ]);
    //Upcoming. - 22.karta
        \App\Models\matches::create([
        'home_team_id' => '2',
        'away_team_id' => '7',
        'date' => '2025-07-04 19:00:00',
        'matchweek' => '22',
        'stadium' => 'LNK Sporta Parks (dabīgais)',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '6',
        'date' => '2025-07-05 18:00:00',
        'matchweek' => '22',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '5',
        'away_team_id' => '8',
        'date' => '2025-07-06 16:00:00',
        'matchweek' => '22',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '9',
        'away_team_id' => '10',
        'date' => '2025-07-06 18:00:00',
        'matchweek' => '22',
        'stadium' => 'Jāņa Skredeļa stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '1',
        'away_team_id' => '4',
        'date' => '2025-07-06 19:00:00',
        'matchweek' => '22',
        'stadium' => 'Skonto stadions',
    ]);
    //Upcoming. - 23.karta
        \App\Models\matches::create([
        'home_team_id' => '7',
        'away_team_id' => '1',
        'date' => '2025-07-19 16:00:00',
        'matchweek' => '23',
        'stadium' => 'Stadions “Daugava”, Liepāja',
    ]);\App\Models\matches::create([
        'home_team_id' => '8',
        'away_team_id' => '2',
        'date' => '2025-07-19 18:00:00',
        'matchweek' => '23',
        'stadium' => 'Jūrmalas pilsētas stadions "Sloka"',
    ]);\App\Models\matches::create([
        'home_team_id' => '3',
        'away_team_id' => '4',
        'date' => '2025-07-20 15:00:00',
        'matchweek' => '23',
        'stadium' => 'Skonto stadions',
    ]);\App\Models\matches::create([
        'home_team_id' => '6',
        'away_team_id' => '9',
        'date' => '2025-07-20 17:00:00',
        'matchweek' => '23',
        'stadium' => 'Zemgales OC',
    ]);\App\Models\matches::create([
        'home_team_id' => '10',
        'away_team_id' => '5',
        'date' => '2025-07-21 18:00:00',
        'matchweek' => '23',
        'stadium' => 'Tukuma pilsētas stadions',
    ]);




    }
}
